SELECT * FROM PROJECT;

SELECT * FROM PCOMMENT;

CREATE VIEW PROJECTVIEW
AS
SELECT P.PID, P.REGID, P.REGDATE, P.DEADLINE, P.CONT1, P.PRODUCERID, COUNT(C.CID) AS COMMENTCNT, MAX(C.REGDATE) AS RECENTUP 
FROM PROJECT P LEFT OUTER JOIN PCOMMENT C ON P.PID = C.PID GROUP BY P.PID, P.REGID, P.REGDATE, P.DEADLINE, P.CONT1, P.PRODUCERID
ORDER BY P.REGDATE DESC;

CREATE VIEW PROJECTCNT
AS;

SELECT P.PID, MAX(C.REGDATE) AS RECENTUP, COUNT(PID)
FROM PROJECT P LEFT OUTER JOIN PCOMMENT C ON P.PID = C.PID GROUP BY P.PID, P.REGID, P.REGDATE, P.DEADLINE, P.CONT1, P.PRODUCERID
ORDER BY P.REGDATE DESC;

SELECT REGDATE FROM (
    
)

SELECT * FROM(
    SELECT ROWNUM AS RNUM, A.*
    FROM ( 조회할 데이터의 쿼리 ) A
    WHERE ROWNUM <= 10+20
) WHERE RNUM > 10;

SELECT REGDATE FROM PCOMMENT WHERE ROWNUM = 1;

SELECT * FROM PROJECTVIEW;

SELECT SYSDATE FROM DUAL;

SELECT COUNT(PID) FROM PROJECTVIEW
WHERE REGID = 'woalskdl' AND RECENTUP BETWEEN SYSDATE-2 AND SYSDATE;

SELECT COUNT(PID) FROM PROJECTVIEW 
WHERE REGID = 'woalskdl' AND DEADLINE BETWEEN SYSDATE AND SYSDATE + 5;

SELECT COUNT(PID) FROM PROJECTVIEW 
WHERE REGID = 'woalskdl';

SELECT COUNT(PID) FROM PROJECTVIEW 
WHERE DIV = 'img';