SELECT * FROM PROJECT;

SELECT * FROM PCOMMENT;

CREATE VIEW PROJECTVIEW
AS
SELECT P.PID, P.REGID, P.REGDATE, P.DEADLINE, P.CONT1, P.PRODUCERID, COUNT(C.CID) AS COMMENTCNT, MAX(C.REGDATE) AS RECENTUP 
FROM PROJECT P LEFT OUTER JOIN PCOMMENT C ON P.PID = C.PID GROUP BY P.PID, P.REGID, P.REGDATE, P.DEADLINE, P.CONT1, P.PRODUCERID
ORDER BY P.REGDATE DESC;

CREATE VIEW PROJECTCNT
AS;

SELECT P.PID, MAX(C.REGDATE) AS RECENTUP, COUNT(PID)
FROM PROJECT P LEFT OUTER JOIN PCOMMENT C ON P.PID = C.PID GROUP BY P.PID, P.REGID, P.REGDATE, P.DEADLINE, P.CONT1, P.PRODUCERID
ORDER BY P.REGDATE DESC;

SELECT REGDATE FROM (
    
)

SELECT * FROM(
    SELECT ROWNUM AS RNUM, A.*
    FROM ( 조회할 데이터의 쿼리 ) A
    WHERE ROWNUM <= 10+20
) WHERE RNUM > 10;

SELECT REGDATE FROM PCOMMENT WHERE ROWNUM = 1;

SELECT * FROM PROJECTVIEW;

SELECT SYSDATE FROM DUAL;

SELECT COUNT(PID) FROM PROJECTVIEW
WHERE REGID = 'woalskdl' AND RECENTUP BETWEEN SYSDATE-2 AND SYSDATE;

SELECT COUNT(PID) FROM PROJECTVIEW 
WHERE REGID = 'woalskdl' AND DEADLINE BETWEEN SYSDATE AND SYSDATE + 5;

SELECT COUNT(PID) FROM PROJECTVIEW 
WHERE REGID = 'woalskdl';

SELECT COUNT(PID) FROM PROJECTVIEW 
WHERE DIV = 'img';

SELECT * FROM MEMBER;

UPDATE MEMBER SET EMAIL='woalskdl@gmail.com' WHERE NAME='남재민';
UPDATE MEMBER SET EMAIL='gilbro@naver.com' WHERE NAME='길브로';
UPDATE MEMBER SET EMAIL='test@gmail.com' WHERE NAME='테스트';
UPDATE MEMBER SET EMAIL='blog@naver.com' WHERE NAME='블로그';
UPDATE MEMBER SET EMAIL='khd@naver.com' WHERE NAME='강호동';
UPDATE MEMBER SET EMAIL='jkh@nate.com' WHERE NAME='조규현';
UPDATE MEMBER SET EMAIL='smh@gmail.com' WHERE NAME='송민호';
UPDATE MEMBER SET EMAIL='pjh@gmail.com' WHERE NAME='표지훈';
UPDATE MEMBER SET EMAIL='ejw@hanmail.net' WHERE NAME='은지원';
UPDATE MEMBER SET EMAIL='lsk@naver.com' WHERE NAME='이수근';

SELECT COUNT(ID) FROM (
    SELECT * FROM MEMBER 
    WHERE ID != 'gilbro'
)WHERE EMAIL = 'woalskdl@gmail.com';